### ISSUE TITLE
Proposal: Add to Resources Section Awesome-Emacs

### ISSUE THREAD

**Issue by agsdot** [picandocodigo/emacs.sexy#18]
Hey, just a proposal here. What do you say about adding [Awesome-Emacs](https://github.com/emacs-tw/awesome-emacs) to the Resource section? Its a nice concise and organized summary of packages.  

So far I'm aware of Awesome Python and Awesome Lua, and while I don't yet code in those languages, I really like the organized break down of different resources available to a language?

If you approve, I can make a pull request.

JL

**Comment by picandocodigo** [comment]
Yes, I think it's a great idea, I didn't know about Awesome-Emacs. Thanks! :+1:

**Comment by agsdot** [comment]
Cool.  I'll work on doing the pull request in the next few days.

**Comment by picandocodigo** [comment]
Awesome, thanks :)

**Comment by agsdot** [comment]
Pull request is in.

**Comment by picandocodigo** [comment]
Merged, thank you!

**Comment by agsdot** [comment]
Your welcome!
