### ISSUE TITLE
Add #div link to icons section for easy link sharing

### ISSUE THREAD

**Issue by plpxsk** [picandocodigo/emacs.sexy#26]
I'd like to suggest adding a #div or similar for easy linking to the icons which are near the middle of the page

I've found myself pointing people to them, and it currently requires pasting link to emacs.sexy and then saying something like "scroll to middle of page to find icons"

**Comment by picandocodigo** [comment]
Thanks for the suggestion! This has been fixed and you can now use: http://emacs.sexy/#icons

**Comment by plpxsk** [comment]
hey @picandocodigo , check it out! 

![top google result](https://cloud.githubusercontent.com/assets/6165713/24276032/10b520e4-0ff1-11e7-96a0-7be300d84dcb.jpg)
