### ISSUE TITLE
Google Hangouts mentioned as XMPP

### ISSUE THREAD

**Issue by Morgensohn** [picandocodigo/emacs.sexy#28]
Are you sure Google Hangouts is actually XMPP? I thought they stopped using XMPP with GTalk.

**Comment by picandocodigo** [comment]
I think you're right. Removing it just in case since I haven't tested this in ages.

**Comment by Morgensohn** [comment]
Thanks for the reply.

Maybe the person who wrote that part of the sentence wanted to say

>  or use the Jabber package to hop on any XMPP service
>   (**similar to** Google Hangouts).

assuming that many people don't unfortunately know or use XMPP services. But it definitely looks less ambiguous now.
