### ISSUE TITLE
French problems...

### ISSUE THREAD

**Issue by fdelbos** [picandocodigo/emacs.sexy#31]
https://github.com/picandocodigo/emacs.sexy/blob/d4ecf9dd54784dcb23cf8a9f04f59ce859fc9e52/index.html#L68

if you mean: "are you a programmer" you should write: "Es-tu un programmeur"

**Comment by picandocodigo** [comment]
Hi @fdelbos, thanks for reporting this!
The phrase is a reference to *[Et tu, Brute?](https://en.wikipedia.org/wiki/Et_tu,_Brute%3F)* in Latin, not French.
But today I learned how to say "are you a programmer" in French though, so thanks for that :smile: :fr:

**Comment by fdelbos** [comment]
Hi, well my bad, it sounds exactly the same way in french... But today I learn some latin!

cheers!
