### ISSUE TITLE
github release to hosting emacs.sexy icons

### ISSUE THREAD

**Issue by avelino** [picandocodigo/emacs.sexy#35]
Today is kept **ZIP** in branch master, will we keep the icons in github relase?
Each isolated file and a bucket (ZIP) with all

**Comment by picandocodigo** [comment]
Hi @avelino,
Thanks for your suggestion! What would be the advantage of having the icons in a release when they're available on the website?

**Comment by avelino** [comment]
Reference use: https://github.com/railwaycat/homebrew-emacsmacport/pull/180

**Comment by picandocodigo** [comment]
Ah, that's great! So you'd be able to install Emacs in MacOS with these icons, right?

I'll add this to the release and let you know once it's done :+1:

**Comment by picandocodigo** [comment]
@avelino [Done](https://github.com/picandocodigo/emacs.sexy/releases/tag/icons)!
