### ISSUE TITLE
Compare value of emacs.sexy and vim.sexy

### ISSUE THREAD

**Issue by Trevoke** [picandocodigo/emacs.sexy#4]
http://vim.sexy/ does a number of things. I mean, it was clearly started half as a joke and half as a response (well, also a joke) to the Atom editor, as evidenced by the link in the bottom to get an invite code to vim.

There are, though, actually some examples of appealing plugins and things to do. Maybe it's in the emacs mentality to say "here are resources, go learn"! Maybe we can, here, do something a little different, and point at specific things.

How about a mode for javascript, and yasnippet, and toggling between buffers, and projectile, and smex?

**Comment by picandocodigo** [comment]
That's my goal with this page yes, making a newcomer find Emacs interesting without telling them "go read the manual".

I added some stuff on [Why Emacs?](http://emacs.sexy/#_why) earlier today. But I think we can do better. Maybe a video showing awesome stuff you can do with Emacs?

I want this site to be collaborative so feel free to do a PR with any cool content :+1:

**Comment by azzamsa** [comment]
@picandocodigo maybe this section https://github.com/Wilfred/remacs/blob/master/README.md#why-emacs can be additional inspiration for you to add into "why emacs?"

Btw, many people love that 'why emacs from remacs'.

**Comment by picandocodigo** [comment]
@azzamsa thanks for sharing the link! I'll add it to the "Why Emacs?" section :+1: 

I'm going to close this issue now, if there's any further suggestions, please open a new issue. Thanks!

**Comment by azzamsa** [comment]
Thanks a TON for emacs.sexy.

It's awesome when people asked "why Emacs", I can just point them to this link :tada:
