### ISSUE TITLE
Linus Torvalds using the same emacs as RMS ? I don't think so.

### ISSUE THREAD

**Issue by YoungFrog** [picandocodigo/emacs.sexy#5]
LT says he uses "uEmacs/PK" and adds : "not to be confused with real emacs, which is the tool of the devil". Listing his name next to RMS is... wow.

Source : https://plus.google.com/+LinusTorvalds/posts/iySKQGtkmtb

**Comment by picandocodigo** [comment]
Good catch, fixed it.
