### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by pank** [picandocodigo/emacs.sexy#7]
Hi

Emacs.sexy is classy and simple and the source is nice and readable and great for learning for people who do not really know much about the new "trends" in html+css+js.  I would like to use parts of emacs.sexy as a "template" for a personal website, especially with @abo-abo's Org source (#2).

Thus, it would be great if you'd specify a license or at least let me know here whether if such usage is acceptable to you.

Thanks,

**Comment by picandocodigo** [comment]
Done, you are free to use it under the terms of the GPLv3.

Great that you found it useful!
